//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avto
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка.
    /// </summary>
    // *** Start programmer edit section *** (Заявка CustomAttributes)

    // *** End programmer edit section *** (Заявка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкаE", new string[] {
            "ID as \'ID\'",
            "Содержание as \'Содержание\'",
            "ДатаСдачи as \'Дата сдачи\'",
            "Студент as \'Студент\'",
            "Студент.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Студент.ФИО"})]
    [MasterViewDefineAttribute("ЗаявкаE", "Студент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ЗаявкаL", new string[] {
            "ID as \'ID\'",
            "Содержание as \'Содержание\'",
            "ДатаСдачи as \'Дата сдачи\'",
            "Студент.ФИО as \'ФИО\'"})]
    public class Заявка : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fСодержание;
        
        private System.DateTime fДатаСдачи;
        
        private IIS.Avto.Студент fСтудент;
        
        // *** Start programmer edit section *** (Заявка CustomMembers)

        // *** End programmer edit section *** (Заявка CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.ID CustomAttributes)

        // *** End programmer edit section *** (Заявка.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.ID Get start)

                // *** End programmer edit section *** (Заявка.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Заявка.ID Get end)

                // *** End programmer edit section *** (Заявка.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.ID Set start)

                // *** End programmer edit section *** (Заявка.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Заявка.ID Set end)

                // *** End programmer edit section *** (Заявка.ID Set end)
            }
        }
        
        /// <summary>
        /// ДатаСдачи.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.ДатаСдачи CustomAttributes)

        // *** End programmer edit section *** (Заявка.ДатаСдачи CustomAttributes)
        public virtual System.DateTime ДатаСдачи
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.ДатаСдачи Get start)

                // *** End programmer edit section *** (Заявка.ДатаСдачи Get start)
                System.DateTime result = this.fДатаСдачи;
                // *** Start programmer edit section *** (Заявка.ДатаСдачи Get end)

                // *** End programmer edit section *** (Заявка.ДатаСдачи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.ДатаСдачи Set start)

                // *** End programmer edit section *** (Заявка.ДатаСдачи Set start)
                this.fДатаСдачи = value;
                // *** Start programmer edit section *** (Заявка.ДатаСдачи Set end)

                // *** End programmer edit section *** (Заявка.ДатаСдачи Set end)
            }
        }
        
        /// <summary>
        /// Содержание.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Содержание CustomAttributes)

        // *** End programmer edit section *** (Заявка.Содержание CustomAttributes)
        [StrLen(255)]
        public virtual string Содержание
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Содержание Get start)

                // *** End programmer edit section *** (Заявка.Содержание Get start)
                string result = this.fСодержание;
                // *** Start programmer edit section *** (Заявка.Содержание Get end)

                // *** End programmer edit section *** (Заявка.Содержание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Содержание Set start)

                // *** End programmer edit section *** (Заявка.Содержание Set start)
                this.fСодержание = value;
                // *** Start programmer edit section *** (Заявка.Содержание Set end)

                // *** End programmer edit section *** (Заявка.Содержание Set end)
            }
        }
        
        /// <summary>
        /// Заявка.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Студент CustomAttributes)

        // *** End programmer edit section *** (Заявка.Студент CustomAttributes)
        [PropertyStorage(new string[] {
                "Студент"})]
        [NotNull()]
        public virtual IIS.Avto.Студент Студент
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Студент Get start)

                // *** End programmer edit section *** (Заявка.Студент Get start)
                IIS.Avto.Студент result = this.fСтудент;
                // *** Start programmer edit section *** (Заявка.Студент Get end)

                // *** End programmer edit section *** (Заявка.Студент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Студент Set start)

                // *** End programmer edit section *** (Заявка.Студент Set start)
                this.fСтудент = value;
                // *** Start programmer edit section *** (Заявка.Студент Set end)

                // *** End programmer edit section *** (Заявка.Студент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаE", typeof(IIS.Avto.Заявка));
                }
            }
            
            /// <summary>
            /// "ЗаявкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаL", typeof(IIS.Avto.Заявка));
                }
            }
        }
    }
}
