//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avto
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Задание.
    /// </summary>
    // *** Start programmer edit section *** (Задание CustomAttributes)

    // *** End programmer edit section *** (Задание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаданиеE", new string[] {
            "ID as \'ID\'",
            "Описание as \'Описание\'",
            "СрокСдачи as \'Срок сдачи\'",
            "Заявка as \'Заявка\'",
            "Заявка.Содержание as \'Содержание\'"}, Hidden=new string[] {
            "Заявка.Содержание"})]
    [MasterViewDefineAttribute("ЗаданиеE", "Заявка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Содержание")]
    [View("ЗаданиеL", new string[] {
            "ID as \'ID\'",
            "Описание as \'Описание\'",
            "СрокСдачи as \'Срок сдачи\'",
            "Заявка.Содержание as \'Содержание\'"})]
    public class Задание : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fОписание;
        
        private System.DateTime fСрокСдачи;
        
        private IIS.Avto.Заявка fЗаявка;
        
        // *** Start programmer edit section *** (Задание CustomMembers)

        // *** End programmer edit section *** (Задание CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Задание.ID CustomAttributes)

        // *** End programmer edit section *** (Задание.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Задание.ID Get start)

                // *** End programmer edit section *** (Задание.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Задание.ID Get end)

                // *** End programmer edit section *** (Задание.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задание.ID Set start)

                // *** End programmer edit section *** (Задание.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Задание.ID Set end)

                // *** End programmer edit section *** (Задание.ID Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Задание.Описание CustomAttributes)

        // *** End programmer edit section *** (Задание.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Задание.Описание Get start)

                // *** End programmer edit section *** (Задание.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Задание.Описание Get end)

                // *** End programmer edit section *** (Задание.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задание.Описание Set start)

                // *** End programmer edit section *** (Задание.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Задание.Описание Set end)

                // *** End programmer edit section *** (Задание.Описание Set end)
            }
        }
        
        /// <summary>
        /// СрокСдачи.
        /// </summary>
        // *** Start programmer edit section *** (Задание.СрокСдачи CustomAttributes)

        // *** End programmer edit section *** (Задание.СрокСдачи CustomAttributes)
        public virtual System.DateTime СрокСдачи
        {
            get
            {
                // *** Start programmer edit section *** (Задание.СрокСдачи Get start)

                // *** End programmer edit section *** (Задание.СрокСдачи Get start)
                System.DateTime result = this.fСрокСдачи;
                // *** Start programmer edit section *** (Задание.СрокСдачи Get end)

                // *** End programmer edit section *** (Задание.СрокСдачи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задание.СрокСдачи Set start)

                // *** End programmer edit section *** (Задание.СрокСдачи Set start)
                this.fСрокСдачи = value;
                // *** Start programmer edit section *** (Задание.СрокСдачи Set end)

                // *** End programmer edit section *** (Задание.СрокСдачи Set end)
            }
        }
        
        /// <summary>
        /// Задание.
        /// </summary>
        // *** Start programmer edit section *** (Задание.Заявка CustomAttributes)

        // *** End programmer edit section *** (Задание.Заявка CustomAttributes)
        [PropertyStorage(new string[] {
                "Заявка"})]
        [NotNull()]
        public virtual IIS.Avto.Заявка Заявка
        {
            get
            {
                // *** Start programmer edit section *** (Задание.Заявка Get start)

                // *** End programmer edit section *** (Задание.Заявка Get start)
                IIS.Avto.Заявка result = this.fЗаявка;
                // *** Start programmer edit section *** (Задание.Заявка Get end)

                // *** End programmer edit section *** (Задание.Заявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задание.Заявка Set start)

                // *** End programmer edit section *** (Задание.Заявка Set start)
                this.fЗаявка = value;
                // *** Start programmer edit section *** (Задание.Заявка Set end)

                // *** End programmer edit section *** (Задание.Заявка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаданиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаданиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаданиеE", typeof(IIS.Avto.Задание));
                }
            }
            
            /// <summary>
            /// "ЗаданиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаданиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаданиеL", typeof(IIS.Avto.Задание));
                }
            }
        }
    }
}
