//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avto
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Курс.
    /// </summary>
    // *** Start programmer edit section *** (Курс CustomAttributes)

    // *** End programmer edit section *** (Курс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КурсE", new string[] {
            "ID as \'ID\'",
            "Название as \'Название\'",
            "Преподаватель as \'Преподаватель\'",
            "Преподаватель.ФИО as \'ФИО\'",
            "Задание as \'Задание\'",
            "Задание.Описание as \'Описание\'"}, Hidden=new string[] {
            "Преподаватель.ФИО",
            "Задание.Описание"})]
    [AssociatedDetailViewAttribute("КурсE", "БДМатериалов", "БДМатериаловE", true, "", "материалы", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("КурсE", "Преподаватель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("КурсE", "Задание", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Описание")]
    [View("КурсL", new string[] {
            "ID as \'ID\'",
            "Название as \'Название\'",
            "Преподаватель.ФИО as \'ФИО\'",
            "Задание.Описание as \'Описание\'"})]
    public class Курс : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНазвание;
        
        private IIS.Avto.Преподаватель fПреподаватель;
        
        private IIS.Avto.Задание fЗадание;
        
        private IIS.Avto.DetailArrayOfБДМатериалов fБДМатериалов;
        
        // *** Start programmer edit section *** (Курс CustomMembers)

        // *** End programmer edit section *** (Курс CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Курс.ID CustomAttributes)

        // *** End programmer edit section *** (Курс.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Курс.ID Get start)

                // *** End programmer edit section *** (Курс.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Курс.ID Get end)

                // *** End programmer edit section *** (Курс.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.ID Set start)

                // *** End programmer edit section *** (Курс.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Курс.ID Set end)

                // *** End programmer edit section *** (Курс.ID Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Название CustomAttributes)

        // *** End programmer edit section *** (Курс.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Название Get start)

                // *** End programmer edit section *** (Курс.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Курс.Название Get end)

                // *** End programmer edit section *** (Курс.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Название Set start)

                // *** End programmer edit section *** (Курс.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Курс.Название Set end)

                // *** End programmer edit section *** (Курс.Название Set end)
            }
        }
        
        /// <summary>
        /// Курс.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Задание CustomAttributes)

        // *** End programmer edit section *** (Курс.Задание CustomAttributes)
        [PropertyStorage(new string[] {
                "Задание"})]
        [NotNull()]
        public virtual IIS.Avto.Задание Задание
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Задание Get start)

                // *** End programmer edit section *** (Курс.Задание Get start)
                IIS.Avto.Задание result = this.fЗадание;
                // *** Start programmer edit section *** (Курс.Задание Get end)

                // *** End programmer edit section *** (Курс.Задание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Задание Set start)

                // *** End programmer edit section *** (Курс.Задание Set start)
                this.fЗадание = value;
                // *** Start programmer edit section *** (Курс.Задание Set end)

                // *** End programmer edit section *** (Курс.Задание Set end)
            }
        }
        
        /// <summary>
        /// Курс.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Преподаватель CustomAttributes)

        // *** End programmer edit section *** (Курс.Преподаватель CustomAttributes)
        [PropertyStorage(new string[] {
                "Преподаватель"})]
        [NotNull()]
        public virtual IIS.Avto.Преподаватель Преподаватель
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Преподаватель Get start)

                // *** End programmer edit section *** (Курс.Преподаватель Get start)
                IIS.Avto.Преподаватель result = this.fПреподаватель;
                // *** Start programmer edit section *** (Курс.Преподаватель Get end)

                // *** End programmer edit section *** (Курс.Преподаватель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Преподаватель Set start)

                // *** End programmer edit section *** (Курс.Преподаватель Set start)
                this.fПреподаватель = value;
                // *** Start programmer edit section *** (Курс.Преподаватель Set end)

                // *** End programmer edit section *** (Курс.Преподаватель Set end)
            }
        }
        
        /// <summary>
        /// Курс.
        /// </summary>
        // *** Start programmer edit section *** (Курс.БДМатериалов CustomAttributes)

        // *** End programmer edit section *** (Курс.БДМатериалов CustomAttributes)
        public virtual IIS.Avto.DetailArrayOfБДМатериалов БДМатериалов
        {
            get
            {
                // *** Start programmer edit section *** (Курс.БДМатериалов Get start)

                // *** End programmer edit section *** (Курс.БДМатериалов Get start)
                if ((this.fБДМатериалов == null))
                {
                    this.fБДМатериалов = new IIS.Avto.DetailArrayOfБДМатериалов(this);
                }
                IIS.Avto.DetailArrayOfБДМатериалов result = this.fБДМатериалов;
                // *** Start programmer edit section *** (Курс.БДМатериалов Get end)

                // *** End programmer edit section *** (Курс.БДМатериалов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.БДМатериалов Set start)

                // *** End programmer edit section *** (Курс.БДМатериалов Set start)
                this.fБДМатериалов = value;
                // *** Start programmer edit section *** (Курс.БДМатериалов Set end)

                // *** End programmer edit section *** (Курс.БДМатериалов Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КурсE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КурсE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КурсE", typeof(IIS.Avto.Курс));
                }
            }
            
            /// <summary>
            /// "КурсL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КурсL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КурсL", typeof(IIS.Avto.Курс));
                }
            }
        }
    }
}
