//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avto
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Материалы.
    /// </summary>
    // *** Start programmer edit section *** (Материалы CustomAttributes)

    // *** End programmer edit section *** (Материалы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МатериалыE", new string[] {
            "ID as \'ID\'",
            "Содержание as \'Содержание\'"})]
    [View("МатериалыL", new string[] {
            "ID as \'ID\'",
            "Содержание as \'Содержание\'"})]
    public class Материалы : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fСодержание;
        
        // *** Start programmer edit section *** (Материалы CustomMembers)

        // *** End programmer edit section *** (Материалы CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Материалы.ID CustomAttributes)

        // *** End programmer edit section *** (Материалы.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Материалы.ID Get start)

                // *** End programmer edit section *** (Материалы.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Материалы.ID Get end)

                // *** End programmer edit section *** (Материалы.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материалы.ID Set start)

                // *** End programmer edit section *** (Материалы.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Материалы.ID Set end)

                // *** End programmer edit section *** (Материалы.ID Set end)
            }
        }
        
        /// <summary>
        /// Содержание.
        /// </summary>
        // *** Start programmer edit section *** (Материалы.Содержание CustomAttributes)

        // *** End programmer edit section *** (Материалы.Содержание CustomAttributes)
        [StrLen(255)]
        public virtual string Содержание
        {
            get
            {
                // *** Start programmer edit section *** (Материалы.Содержание Get start)

                // *** End programmer edit section *** (Материалы.Содержание Get start)
                string result = this.fСодержание;
                // *** Start programmer edit section *** (Материалы.Содержание Get end)

                // *** End programmer edit section *** (Материалы.Содержание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материалы.Содержание Set start)

                // *** End programmer edit section *** (Материалы.Содержание Set start)
                this.fСодержание = value;
                // *** Start programmer edit section *** (Материалы.Содержание Set end)

                // *** End programmer edit section *** (Материалы.Содержание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МатериалыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалыE", typeof(IIS.Avto.Материалы));
                }
            }
            
            /// <summary>
            /// "МатериалыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалыL", typeof(IIS.Avto.Материалы));
                }
            }
        }
    }
}
