//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avto
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Преподаватель.
    /// </summary>
    // *** Start programmer edit section *** (Преподаватель CustomAttributes)

    // *** End programmer edit section *** (Преподаватель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПреподавательE", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'"})]
    [View("ПреподавательL", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'"})]
    public class Преподаватель : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fФИО;
        
        // *** Start programmer edit section *** (Преподаватель CustomMembers)

        // *** End programmer edit section *** (Преподаватель CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Преподаватель.ID CustomAttributes)

        // *** End programmer edit section *** (Преподаватель.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Преподаватель.ID Get start)

                // *** End programmer edit section *** (Преподаватель.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Преподаватель.ID Get end)

                // *** End programmer edit section *** (Преподаватель.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Преподаватель.ID Set start)

                // *** End programmer edit section *** (Преподаватель.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Преподаватель.ID Set end)

                // *** End programmer edit section *** (Преподаватель.ID Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Преподаватель.ФИО CustomAttributes)

        // *** End programmer edit section *** (Преподаватель.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Преподаватель.ФИО Get start)

                // *** End programmer edit section *** (Преподаватель.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Преподаватель.ФИО Get end)

                // *** End programmer edit section *** (Преподаватель.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Преподаватель.ФИО Set start)

                // *** End programmer edit section *** (Преподаватель.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Преподаватель.ФИО Set end)

                // *** End programmer edit section *** (Преподаватель.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПреподавательE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПреподавательE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПреподавательE", typeof(IIS.Avto.Преподаватель));
                }
            }
            
            /// <summary>
            /// "ПреподавательL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПреподавательL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПреподавательL", typeof(IIS.Avto.Преподаватель));
                }
            }
        }
    }
}
