//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avto
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Студент.
    /// </summary>
    // *** Start programmer edit section *** (Студент CustomAttributes)

    // *** End programmer edit section *** (Студент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтудентE", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'"})]
    [View("СтудентL", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'"})]
    public class Студент : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fФИО;
        
        // *** Start programmer edit section *** (Студент CustomMembers)

        // *** End programmer edit section *** (Студент CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Студент.ID CustomAttributes)

        // *** End programmer edit section *** (Студент.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Студент.ID Get start)

                // *** End programmer edit section *** (Студент.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Студент.ID Get end)

                // *** End programmer edit section *** (Студент.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.ID Set start)

                // *** End programmer edit section *** (Студент.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Студент.ID Set end)

                // *** End programmer edit section *** (Студент.ID Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Студент.ФИО CustomAttributes)

        // *** End programmer edit section *** (Студент.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Студент.ФИО Get start)

                // *** End programmer edit section *** (Студент.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Студент.ФИО Get end)

                // *** End programmer edit section *** (Студент.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.ФИО Set start)

                // *** End programmer edit section *** (Студент.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Студент.ФИО Set end)

                // *** End programmer edit section *** (Студент.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтудентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтудентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтудентE", typeof(IIS.Avto.Студент));
                }
            }
            
            /// <summary>
            /// "СтудентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтудентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтудентL", typeof(IIS.Avto.Студент));
                }
            }
        }
    }
}
